### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Argeare5** [mattkrco/plyrtesting#1]
Hello I fixed your issue with action buttons, I can push fix, please give me access for push, and you don't need to pay

**Comment by mattkrco** [comment]
Just added you as a collaborator, if you have a fix it would be much appreciated

**Comment by Argeare5** [comment]
I still can't push, But I'll just write what you need to do

**Comment by Argeare5** [comment]
first install
"plyr-react": "^4.0.0-alpha.5",

**Comment by Argeare5** [comment]
and index.js file looks like this

`import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useCallback, useRef} from 'react';
import Plyr from "plyr-react"
import "plyr-react/dist/plyr.css"

const plyrProps = {
  source: {
    type: "youtube",
    sources: [
      {
        src: "MzYD56hKF-8",
        provider: "youtube"
      }
    ],
  }, // https://github.com/sampotts/plyr#the-source-setter
  // for youtube source this can help https://github.com/chintan9/plyr-react/issues/715
  options: undefined, // https://github.com/sampotts/plyr#options
}

export default function Home() {
  const player = useRef();

  const togglePlay = useCallback(() => {
    const plyrRef = player.current;
    if (!plyrRef) return;
    plyrRef.plyr.togglePlay();
  }, [player]);

  const skip = useCallback((timeToForward) => {
    const plyrRef = player.current;
    if (!plyrRef) return;
    plyrRef.plyr.forward(timeToForward);
  }, [player]);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Plyr ref={player} {...plyrProps} />

        <button onClick={togglePlay}>togglePlay</button>
        <button onClick={() => skip(10)}>Skip ahead</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}`

**Comment by Argeare5** [comment]
Your mistake was that an `div` has nothing to know about the `plyr`, so `ref` was `undefined`, it is impossible to rewrite ref, when you use `useRef`, in the way that you did it
Therefore, it is worth installing the module of `plyr` specifically for the react and then process the functions you need

I created PR with fix, I think you will figure it out further

I also advise you to add `TypeScript` to the project which you would immediately understand what types you will have in variables or in functions

good luck @mattkrco

**Comment by mattkrco** [comment]
Thanks, I'm new to React so it would have taken me hours to figure that out
